[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-L", "native=/usr/lib", "-Z", "mir-opt-level=3", "-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Z", "mir-opt-level=3", "-C", "target-cpu=native"]
